apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: resume-api-dotnetcore-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: resume-api-dotnetcore-deployment
    spec:
      containers:
      - name: resume-api-dotnetcore
        image: us.gcr.io/%GCLOUD_PROJECT_ID%/resume-api-dotnetcore:%GIT_COMMIT_SHA%
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /alive
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /alive
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "50m"
            memory: "250Mi"
          requests:
            cpu: "10m"
            memory: "150Mi"
      